model:
  base_learning_rate: 1.0e-06
  target: models.VIGOR_geo_ldm.txt_control.Boost_Sat2Den_ddpm
  params:
    AE_config:
      target: models.autoencoder.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: models.loss_fun.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 0.000001
            disc_weight: 0.5
    AE_ckpt_path: ./ckpt/sd-v1-4.ckpt
    DDPM_config:
        target: models.VIGOR_geo_ldm_diffusion.latent_diffusion.DDPM
        params:
            linear_start: 0.00085
            linear_end: 0.012
            timesteps: 1000
            unet_config:
              target: models.VIGOR_geo_ldm_diffusion.openaimodel.UNetModel
              params:
                image_size: 32
                in_channels: 4
                out_channels: 4
                model_channels: 320
                attention_resolutions:
                - 4
                - 2
                - 1
                num_res_blocks: 2
                channel_mult:
                - 1
                - 2
                - 4
                - 4
                num_heads: 8
                use_spatial_transformer: true
                transformer_depth: 1
                context_dim: 768
                use_checkpoint: true
                legacy: False              
            control_grd:
              target: models.VIGOR_geo_ldm.grd_condition_model.UNetModel 
              params:
                  image_size: 32
                  in_channels: 4
                  out_channels: 4
                  model_channels: 320
                  attention_resolutions:
                  # note: this isn\t actually the resolution but
                  # the downsampling factor, i.e. this corresnponds to
                  # attention on spatial resolution 8,16,32, as the
                  # spatial reolution of the latents is 64 for f4
                  - 4
                  - 2
                  - 1
                  num_res_blocks: 2
                  channel_mult:
                  - 1
                  - 2
                  - 4
                  - 4
                  num_heads: 8
                  use_spatial_transformer: true
                  transformer_depth: 1
                  context_dim: 768
                  use_checkpoint: true
                  legacy: False
              
    Condition_config_grd:
        target: ldm.modules.encoders.modules.CLIPVisionEmbedder
    Condition_config_sat:
        target: models.VIGOR_geo_ldm.condition_model.VIT_224
    pre_sat2grd_model_path:


    # Condition_config_txt:
    #     target: ldm.modules.encoders.modules.BERTEmbedder
    #     params:
    #       n_embed: 1280
    #       n_layer: 32
    pre_ldm_model_path: ./ckpt/sd-v1-4.ckpt
    
    scale_factor: 0.18215
    Condition_config_txt:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
    

      
data:
  target: dataloader.dataload.DataModuleFromConfig
  params:
    batch_size: 32      
    wrap: True
    train:
      target: dataloader.VIGOR_corr.VIGORDataset
      params:
        root: './dataset/VIGOR'
        split: 'same'
        train: True
    test:
      target: dataloader.VIGOR_corr.VIGORDataset
      params:
        root: './dataset/VIGOR'
        split: 'same'
        train: False

lightning:
  callbacks:
    image_logger:
      target: utils.callback.callback.ImageLogger
      params:
        batch_frequency: 4000
        max_images: 8

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
