model:
  base_learning_rate: 7.2e-05
  target: models.feat_geo_autoencoder.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    image_key: "pano"
    outputs_key: "pano"
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 30001
        kl_weight: 1.0e-06
        disc_weight: 0.5

    ddconfig:
      double_z: True
      pre_train: True
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: dataset.dataloader.dataload.DataModuleFromConfig
  params:
    batch_size: 12
    # batch_size: 30
    wrap: True
    train:
      target: dataset.dataloader.CVUSA.Dataset
      params:
        data_root: ./dataset/CVUSA/
        sat_size: [256, 256]
        pano_size: [512, 128]
        sky_mask: True
        histo_mode: rgb
        split: train
    test:
      target: dataset.dataloader.CVUSA.Dataset
      params:
        data_root: ./dataset/CVUSA/
        sat_size: [256, 256]
        pano_size: [512, 128]
        sky_mask: True
        histo_mode: rgb
        split: val

lightning:
  callbacks:
    image_logger:
      target: utils.callback.callback.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8

  trainer:
    benchmark: True
    accumulate_grad_batches: 2

